# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
    secret_key_base: fc8938b5f961ef7ebbb248ecd1bf99b0f569870e43ab6432206d7fb6a4ce04737d7472ecfeaec2f6d077bbdc3b7620f298d8d06132d429198db2bf18522a9730
    client_id: 776741070724-bk9nk2m2k9elkgfac8i3dvgnf6oth4v3.apps.googleusercontent.com
    client_secret: 8iAXx_djMVQE4qgKY3i1Ye5A
test:
    secret_key_base: f2d584254b80c30b38e33ec65f4cb2cce8383b6e82e232a76b486eed026ab3865c400dc4bf69c8948a16acbdf93752ee8591e9d316430544a10b9683cf798598
    client_id: 776741070724-bk9nk2m2k9elkgfac8i3dvgnf6oth4v3.apps.googleusercontent.com
    client_secret: 8iAXx_djMVQE4qgKY3i1Ye5A
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
    secret_key_base: f2d584254b80c30b38e33ec65f4cb2cce8383b6e82e232a76b486eed026ab3865c400dc4bf69c8948a16acbdf93752ee8591e9d316430544a10b9683cf798598
    client_id: 776741070724-bk9nk2m2k9elkgfac8i3dvgnf6oth4v3.apps.googleusercontent.com
    client_secret: 8iAXx_djMVQE4qgKY3i1Ye5A